SELECT 
    ID,
    DEPTO,
    SUM(QUANTIDADE) AS QUANTIDADE,
    SUM(VALOR_UNITARIO * QUANTIDADE) AS VALOR_TOTAL,
    CASE 
        WHEN SUM(VALOR_UNITARIO * QUANTIDADE) <= 1000 THEN 'Básico'
        WHEN SUM(VALOR_UNITARIO * QUANTIDADE) > 1000 AND SUM(VALOR_UNITARIO * QUANTIDADE) <= 2000 THEN 'Prata'
        WHEN SUM(VALOR_UNITARIO * QUANTIDADE) > 2000 AND SUM(VALOR_UNITARIO * QUANTIDADE) <= 5000 THEN 'Ouro'
        WHEN SUM(VALOR_UNITARIO * QUANTIDADE) > 5000 THEN 'Super'
    END AS FAIXA
FROM 
    pm_web.pm_web_resultado
GROUP BY 
    ID,DEPTO
ORDER BY 
    Valor_total DESC;
